name: WorkShop Build and Publish

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  workshop:
    runs-on: windows-2022
    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Build
        shell: cmd
        run: |
          ./scripts/build.bat

      - name: Publish
        shell: cmd
        run: |
          7z a -t7z workshop-${{ github.run_id }}.7z ./release/*

      - name: Create Release And Upload Assets
        uses: softprops/action-gh-release@v3
        with:
          files: |
            workshop-${{ github.run_id }}.7z
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}